------------------------------------------
Current Day is   Mon Mar 11 18:57:38 2019
Max header files in the Project -       9
Max cpp files in the Project    -       5
Max qml files in the Project    -       0
Max tests files in the Project  -      -1
Max files in the Project        -      14
Max qml lines in the Project    -       0
Max tests in the Project        -       0
Max lines in the Project        -     663
Max symbols in the Project      -   19665
